name: techniques
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyterlab
  - pip
  - dask
  - dask-ml
  - nodejs
  - dask_labextension
  - pip:
    - pyspark
#    - toree
#    - gym
    - ray[rllib]
    - tensorflow
#    - torch
#    - torchvision
#    - cpuonly
#    - jupyter-server-proxy
