name: techniques
channels:
  - conda-forge
dependencies:
  - python=3.7
  - jupyterlab
  - pip
#  - dask
#  - dask-ml
#  - nodejs
#  - dask_labextension
#  - pip:
#    - pyspark
#    - tensorflow
#    - gym
    - ray[rllib]
